version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    environment:
      - REDIS_PASSWORD=password

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: scraping
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: poweruser12345

networks:
  mynetwork:
